CREATE DATABASE "EBuy.Ecommerce";
USE "EBuy.Ecommerce";

CREATE TABLE Marca (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Produto (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(500) NULL,
	IdMarca INT NOT NULL FOREIGN KEY REFERENCES Marca(Id)
);

CREATE TABLE Categoria (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE CategoriaProduto (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdProduto INT NOT NULL FOREIGN KEY REFERENCES Produto(Id),
	IdCategoria INT NOT NULL FOREIGN KEY REFERENCES Categoria(Id)
);

CREATE TABLE ProdutoApresentacao (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdProduto INT NOT NULL FOREIGN KEY REFERENCES Produto(Id),
	Descricao VARCHAR(500) NULL,
	Valor DECIMAL(18,2) NOT NULL
);

CREATE TABLE ProdutoApresentacaoDetalhe(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdProdutoApresentacao INT NOT NULL FOREIGN KEY REFERENCES ProdutoApresentacao(Id),
	Item VARCHAR(500) NULL, -- REALMENTE NÃO SEI O QUE É ISSO
	Descricao VARCHAR(255) NULL
);

CREATE TABLE Cliente (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	DataCadastro DATETIME NOT NULL
);

CREATE TABLE UnidadeFederacao (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Sigla VARCHAR(2) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
);

CREATE TABLE Cidade (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	IdUnidadeFederacao INT NOT NULL FOREIGN KEY REFERENCES UnidadeFederacao(Id)
);

CREATE TABLE ClienteEndereco (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente(Id),
	Logradouro VARCHAR (255) NOT NULL,
	Numero INT NOT NULL,
	Complemento VARCHAR(255) NULL,
	Bairro VARCHAR(100) NOT NULL,
	CEP VARCHAR(20) NOT NULL,
	IdCidade INT NOT NULL FOREIGN KEY REFERENCES Cidade(Id),
	NomeRecebedor VARCHAR(100) NOT NULL,
	EhEnderecoPadrao BIT NOT NULL
);

CREATE TABLE Carrinho (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente(Id),
	IdProdutoApresentacao INT NOT NULL FOREIGN KEY REFERENCES ProdutoApresentacao(Id),
	Valor DECIMAL(18,2) NULL,
	Qtde INT NOT NULL,
	Parcelas INT NULL,
	GerouPedido BIT NOT NULL
);

CREATE TABLE MetodoPagamento (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE PedidoVendaStatus (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE PedidoVenda (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	NumeroPedido INT NULL,
	Data DATETIME NOT NULL,
	DataPrevistaEntrega DATETIME NOT NULL,
	IdCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente(Id),
	IdEnderecoEntrega INT NOT NULL FOREIGN KEY REFERENCES ClienteEndereco(Id),
	IdMetodoPagamento INT NOT NULL FOREIGN KEY REFERENCES MetodoPagamento(Id),
	ValorProdutos DECIMAL(18,2) NULL,
	ValorFrete DECIMAL(18,2) NULL,
	IdStatus INT NOT NULL FOREIGN KEY REFERENCES PedidoVendaStatus(Id)
);

CREATE TABLE PedidoVendaProduto (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdPedidoVenda INT NOT NULL FOREIGN KEY REFERENCES PedidoVenda(Id),
	IdProdutoApresentacao INT NOT NULL FOREIGN KEY REFERENCES ProdutoApresentacao(Id),
	Qtde INT NOT NULL,
	Valor DECIMAL(18,2) NULL
);



